. /Users/max/.no-mistakes/evidence/01M4C13V6870VXRNTBVHEHM9PQ/harness/defs.sh
test_merge_waiting_for_its_turn_refuses_without_touching_the_forge
test_a_merge_on_another_repository_never_waits
test_a_crashed_holder_never_wedges_the_line
test_a_reused_pid_never_keeps_a_dead_ticket_in_line
test_an_unreadable_identity_never_evicts_a_live_ticket
test_a_reused_pid_never_keeps_a_dead_holders_turn
test_a_head_of_line_refusal_names_the_held_turn
test_the_turn_wait_restarts_whenever_the_line_moves
test_two_ready_pull_requests_merge_oldest_first_and_one_at_a_time
